#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# This wizard collects everything the release workflow needs in order to sign
# DIN Replicator, and stores each value as a GitHub Actions secret on the
# project repository. It signs nothing itself. docs/releasing.md says what
# each secret is used for.
#
# Two unrelated certificates are involved:
#   - macOS: an Apple "Developer ID Application" certificate that lives in
#     this Mac's keychain, plus an Apple account allowed to ask Apple to
#     notarize a build.
#   - Windows: an Azure Artifact Signing certificate profile, which Microsoft
#     used to call Azure Trusted Signing, plus a Microsoft Entra ID app
#     registration allowed to sign with it. The private key never leaves
#     Azure, so there is no key file to handle.
#
# No value is written to disk. Secrets live in shell variables for the length
# of the run and go straight to GitHub. The wizard never prints one back, so
# a mistyped value shows up as a failing release build rather than on screen.
# Re-running the wizard overwrites the secrets, which is how a wrong value
# gets corrected.
#
# The Azure half can stall for days at identity validation, which Microsoft
# performs and which only the Azure portal can start. The wizard stops there
# and stores no Azure secret until a certificate profile exists, so a release
# built in the meantime is unsigned on Windows rather than broken. Run the
# wizard again once validation completes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# Every `gh` call in this run targets the project repository, wherever the
# wizard was started from.
export GH_REPO="Fountain-Bio/din-replicator"

# Scratch space for the exported certificate, removed however the run ends.
WORK_DIR=$(mktemp -d)
trap 'rm -rf "$WORK_DIR"' EXIT

# The library offers previously saved values as defaults by reading a .env
# file. This wizard saves nothing, so point that lookup at the scratch
# directory instead of at the repository.
ENV_FILE="$WORK_DIR/unused.env"

# Apple allows code signing only on a Mac, so the Apple half is skipped
# elsewhere and the Azure half still runs.
DO_APPLE=true
if [[ "$(uname -s)" != "Darwin" ]]; then
  DO_APPLE=false
fi

# Set to false as soon as an Azure step cannot finish. The Azure secrets are
# stored only when all of them are real.
DO_AZURE=true

# --apple-only and --azure-only run one half of the wizard. The two halves
# store their secrets independently, so either can be finished on its own.
for arg in "$@"; do
  case "$arg" in
    --apple-only) DO_AZURE=false ;;
    --azure-only) DO_APPLE=false ;;
    -h|--help)
      printf 'usage: %s [--apple-only | --azure-only]\n' "$0"
      exit 0
      ;;
    *) printf 'unknown option: %s\n' "$arg" >&2; exit 2 ;;
  esac
done

# Command group of the Azure signing CLI extension. Microsoft renamed the
# service, and both names are still published, so stage 7 picks whichever one
# this machine can install.
AZ_SIGNING="artifact-signing"

# skipped_stage "reason" fills in a stage that cannot run on this machine.
skipped_stage() {
  warn "skipped: $1"
  SKIPPED+=("$1")
  pause "Press Enter for the next stage"
}

# developer_id_identities lists the Developer ID Application identities this
# Mac can sign with, one name per line.
developer_id_identities() {
  security find-identity -v -p codesigning 2>/dev/null \
    | sed -n 's/^ *[0-9][0-9]*) [0-9A-Fa-f]* "\(Developer ID Application:.*\)"$/\1/p' \
    | awk '!seen[$0]++'
}

banner "DIN Replicator release signing"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Apple: the Developer ID Application certificate"
APPLE_IDENTITY=""
if [[ "$DO_APPLE" != true ]]; then
  skipped_stage "the Apple stages need a Mac"
else
  say "A Developer ID Application certificate signs apps distributed outside"
  say "the Mac App Store. Without one, macOS refuses to open the app."
  printf '\n'

  identity_list=$(developer_id_identities || true)
  if [[ -z "$identity_list" ]]; then
    say "This Mac has no Developer ID Application certificate yet."
    printf '\n'
    if ! confirm "Do you already have a paid Apple Developer Program membership?"; then
      step "Enrol in the Apple Developer Program. It costs 99 USD a year and"
      step "  Apple can take a day or two to approve it."
      open_url "https://developer.apple.com/programs/enroll/"
      pause "Press Enter once your membership is active"
    fi
    step "Open Xcode, then Settings > Accounts."
    step "Select your Apple Account and click Manage Certificates."
    step "Click the + button at the bottom left and choose"
    step "  Developer ID Application."
    note "No Xcode? Use Keychain Access > Certificate Assistant > Request a"
    note "Certificate From a Certificate Authority to make a"
    note ".certSigningRequest, upload it in the developer portal, pick"
    note "Developer ID Application, then download and double-click the .cer."
    open_url "https://developer.apple.com/account/resources/certificates/list"
    pause "Press Enter once the certificate exists"
    identity_list=$(developer_id_identities || true)
  fi

  if [[ -z "$identity_list" ]]; then
    warn "security find-identity -v -p codesigning still lists no Developer ID"
    warn "Application identity. The certificate and its private key both have"
    warn "to be in this user's login keychain."
    SKIPPED+=("the Apple secrets, because no signing identity was found")
    DO_APPLE=false
    pause "Press Enter for the next stage"
  else
    identity_count=$(printf '%s\n' "$identity_list" | wc -l | tr -d ' ')
    if [[ "$identity_count" == "1" ]]; then
      APPLE_IDENTITY="$identity_list"
      printf '  %s✓ found%s %s\n' "$GREEN" "$RESET" "$APPLE_IDENTITY"
    else
      say "This Mac can sign with more than one of them:"
      printf '%s\n' "$identity_list" | cat -n
      ask IDENTITY_CHOICE "Type the number of the one to use:"
      APPLE_IDENTITY=$(printf '%s\n' "$identity_list" | sed -n "${IDENTITY_CHOICE}p")
      if [[ -z "$APPLE_IDENTITY" ]]; then
        warn "that is not one of the numbers listed"
        exit 1
      fi
      printf '  %s✓ using%s %s\n' "$GREEN" "$RESET" "$APPLE_IDENTITY"
    fi
    pause "Press Enter for the next stage"
  fi
fi

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Apple: export the certificate for the build runner"
APPLE_CERTIFICATE=""
APPLE_CERTIFICATE_PASSWORD=""
if [[ "$DO_APPLE" != true ]]; then
  skipped_stage "no Apple certificate to export"
else
  say "The GitHub runner is a fresh Mac with an empty keychain, so it needs"
  say "the certificate and its private key as one .p12 file, base64 encoded."
  printf '\n'
  ask_secret APPLE_CERTIFICATE_PASSWORD "Choose a password to lock the .p12 file with:"
  if [[ -z "$APPLE_CERTIFICATE_PASSWORD" ]]; then
    warn "the .p12 password cannot be empty"
    exit 1
  fi

  p12_path="$WORK_DIR/certificate.p12"
  printf '\n'
  say "The wizard can run the export for you. macOS asks you to allow it, once"
  say "per key, in a dialog that wants your login password."
  note "That route exports every code signing identity in your login keychain,"
  note "not only the Developer ID one. The release workflow picks the Developer"
  note "ID Application identity out of the file by name."
  if confirm "Export it automatically?"; then
    default_keychain=$(security default-keychain -d user | tr -d ' "')
    if ! security export -k "$default_keychain" -t identities -f pkcs12 \
        -P "$APPLE_CERTIFICATE_PASSWORD" -o "$p12_path" >/dev/null 2>&1; then
      warn "security export failed, so export it by hand instead"
      rm -f "$p12_path"
    fi
  fi

  if [[ ! -s "$p12_path" ]]; then
    printf '\n'
    step "Open Keychain Access, click the login keychain, then My Certificates."
    step "Find the row named: $APPLE_IDENTITY"
    step "Expand it, right-click the key inside it, and choose Export."
    step "Save a .p12 file and give it the password you just chose."
    open_url "file:///System/Applications/Utilities/Keychain%20Access.app"
    ask P12_SOURCE "Paste the full path of the .p12 file you saved:"
    P12_SOURCE="${P12_SOURCE/#\~/$HOME}"
    if [[ ! -s "$P12_SOURCE" ]]; then
      warn "there is no file at that path"
      exit 1
    fi
    cp "$P12_SOURCE" "$p12_path"
  fi

  # A PKCS#12 file is DER, so it starts with a SEQUENCE tag and a long-form
  # length. Catching the wrong file here beats a failing release build.
  if [[ "$(head -c 2 "$p12_path" | od -An -tx1 | tr -d ' ')" != "3082" ]]; then
    warn "that file is not a .p12 certificate bundle"
    exit 1
  fi

  APPLE_CERTIFICATE=$(openssl base64 -A -in "$p12_path")
  printf '%s' "$APPLE_CERTIFICATE" | openssl base64 -d -A -out "$WORK_DIR/roundtrip.p12"
  if ! cmp -s "$p12_path" "$WORK_DIR/roundtrip.p12"; then
    warn "the base64 text does not decode back to the .p12 file"
    exit 1
  fi
  printf '  %s✓ encoded%s %s bytes, and the text decodes back to the same file\n' \
    "$GREEN" "$RESET" "$(wc -c < "$p12_path" | tr -d ' ')"
  pause "Press Enter for the next stage"
fi

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Apple: the build runner's keychain password"
KEYCHAIN_PASSWORD=""
if [[ "$DO_APPLE" != true ]]; then
  skipped_stage "no Apple certificate to unlock"
else
  say "The release job creates a throwaway keychain on the runner to hold the"
  say "certificate for the length of one build. That keychain needs a"
  say "password, which protects nothing outside the runner, so the wizard"
  say "picks a random one."
  KEYCHAIN_PASSWORD=$(openssl rand -base64 24)
  printf '  %s✓ generated%s a random keychain password\n' "$GREEN" "$RESET"
  pause "Press Enter for the next stage"
fi

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Apple: the Team ID"
APPLE_TEAM_ID=""
if [[ "$DO_APPLE" != true ]]; then
  skipped_stage "no Apple team to identify"
else
  say "Apple needs the Team ID to notarize a build. Every Developer ID"
  say "Application certificate ends with it, in brackets."
  APPLE_TEAM_ID=$(printf '%s' "$APPLE_IDENTITY" | sed -n 's/.*(\([A-Z0-9]\{10\}\))$/\1/p')
  if [[ -n "$APPLE_TEAM_ID" ]]; then
    printf '  %s✓ read%s the Team ID out of the certificate name\n' "$GREEN" "$RESET"
  else
    step "Sign in and read the Team ID from the Membership details card."
    open_url "https://developer.apple.com/account#MembershipDetailsCard"
    ask APPLE_TEAM_ID "Paste the Team ID:"
  fi
  if [[ ! "$APPLE_TEAM_ID" =~ ^[A-Z0-9]{10}$ ]]; then
    warn "a Team ID is ten upper case letters and digits"
    exit 1
  fi
  pause "Press Enter for the next stage"
fi

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Apple: the account that asks for notarization"
APPLE_ID=""
APPLE_PASSWORD=""
if [[ "$DO_APPLE" != true ]]; then
  skipped_stage "no Apple account to notarize with"
else
  say "Notarization is Apple scanning the signed app and issuing a ticket for"
  say "it. Without a ticket macOS warns whoever downloads the app. Apple"
  say "rejects your account password here, so this needs an app-specific"
  say "password."
  printf '\n'
  step "Sign in at appleid.apple.com, open Sign-In and Security, then"
  step "  App-Specific Passwords."
  step "Click the + button, name it something like din-replicator-notarize,"
  step "  and copy the password Apple shows. Apple shows it only once."
  open_url "https://appleid.apple.com/account/manage"
  ask APPLE_ID "Paste the Apple account email address:"
  ask_secret APPLE_PASSWORD "Paste the app-specific password:"
  if [[ -z "$APPLE_ID" || -z "$APPLE_PASSWORD" ]]; then
    warn "both the email address and the app-specific password are needed"
    exit 1
  fi
  pause "Press Enter for the next stage"
fi

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Apple: check the notarization credentials"
if [[ "$DO_APPLE" != true ]]; then
  skipped_stage "no Apple credentials to check"
else
  say "Asking Apple for this account's notarization history proves the three"
  say "values work together. An empty history counts as a pass."
  if xcrun notarytool history --apple-id "$APPLE_ID" --password "$APPLE_PASSWORD" \
      --team-id "$APPLE_TEAM_ID" >/dev/null 2>&1; then
    printf '  %s✓ Apple accepted%s the account, the app-specific password and the Team ID\n' \
      "$GREEN" "$RESET"
  else
    warn "Apple rejected them. The usual causes are the account password"
    warn "pasted instead of an app-specific password, an app-specific password"
    warn "that has been revoked, or an Apple account that is not a member of"
    warn "team $APPLE_TEAM_ID."
    confirm "Store them anyway and fix it later?" || exit 1
  fi
  printf '\n'
  say "Storing the six macOS secrets on $GH_REPO now, so the Apple half is"
  say "complete even if the Azure half stops part way."
  set_secret APPLE_CERTIFICATE "$APPLE_CERTIFICATE"
  set_secret APPLE_CERTIFICATE_PASSWORD "$APPLE_CERTIFICATE_PASSWORD"
  set_secret KEYCHAIN_PASSWORD "$KEYCHAIN_PASSWORD"
  set_secret APPLE_ID "$APPLE_ID"
  set_secret APPLE_PASSWORD "$APPLE_PASSWORD"
  set_secret APPLE_TEAM_ID "$APPLE_TEAM_ID"
  APPLE_SECRETS_STORED=true
  pause "Press Enter for the next stage"
fi

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Azure: sign in and prepare the subscription"
if ! command -v az >/dev/null 2>&1; then
  warn "the Azure CLI is not installed. Install it with: brew install azure-cli"
  DO_AZURE=false
  skipped_stage "the Azure stages, because the Azure CLI is missing"
else
  if ! az account show >/dev/null 2>&1; then
    say "Signing you in to Azure. A browser window opens."
    az login --only-show-errors >/dev/null || true
  fi
  if ! az account show >/dev/null 2>&1; then
    warn "still not signed in to Azure"
    DO_AZURE=false
    skipped_stage "the Azure stages, because the Azure CLI is not signed in"
  else
    subscription_name=$(az account show --query name -o tsv)
    printf '  %s✓ signed in%s to the subscription: %s\n' "$GREEN" "$RESET" "$subscription_name"
    say "Everything the wizard creates goes into this subscription."
    note "Change it first with: az account set -s <name or id>"
    if ! confirm "Use this subscription?"; then
      warn "run 'az account set -s <name or id>' and start the wizard again"
      exit 1
    fi

    # Azure will not create a signing account until the resource provider that
    # supplies it is registered on the subscription. Registration is a one-off
    # per subscription and takes a minute or two.
    provider_state=$(az provider show --namespace Microsoft.CodeSigning \
      --query registrationState -o tsv 2>/dev/null || true)
    if [[ "$provider_state" != "Registered" ]]; then
      say "Registering the Microsoft.CodeSigning resource provider. This takes"
      say "a minute or two."
      az provider register --namespace Microsoft.CodeSigning --wait --only-show-errors || true
      provider_state=$(az provider show --namespace Microsoft.CodeSigning \
        --query registrationState -o tsv 2>/dev/null || true)
    fi
    if [[ "$provider_state" == "Registered" ]]; then
      printf '  %s✓ Microsoft.CodeSigning%s is registered\n' "$GREEN" "$RESET"
    else
      warn "Microsoft.CodeSigning is $provider_state, so account creation may fail"
    fi

    # Microsoft renamed Trusted Signing to Artifact Signing and publishes an
    # extension under each name. Prefer the current one.
    if ! az extension show --name artifact-signing >/dev/null 2>&1; then
      az extension add --name artifact-signing --only-show-errors >/dev/null 2>&1 || true
    fi
    if az extension show --name artifact-signing >/dev/null 2>&1; then
      AZ_SIGNING="artifact-signing"
    else
      az extension add --name trustedsigning --only-show-errors >/dev/null 2>&1 || true
      if az extension show --name trustedsigning >/dev/null 2>&1; then
        AZ_SIGNING="trustedsigning"
      else
        warn "neither the artifact-signing nor the trustedsigning CLI extension"
        warn "would install, so the remaining Azure steps have to be done in"
        warn "the portal at https://portal.azure.com"
        DO_AZURE=false
      fi
    fi
    if [[ "$DO_AZURE" == true ]]; then
      printf '  %s✓ using%s the "az %s" commands\n' "$GREEN" "$RESET" "$AZ_SIGNING"
    fi
    pause "Press Enter for the next stage"
  fi
fi

# ── Stage 8 ───────────────────────────────────────────────────────────────
stage "Azure: the Artifact Signing account"
AZURE_ARTIFACT_SIGNING_ACCOUNT=""
AZURE_ARTIFACT_SIGNING_ENDPOINT=""
AZURE_RESOURCE_GROUP=""
if [[ "$DO_AZURE" != true ]]; then
  skipped_stage "no Azure CLI to create a signing account with"
else
  say "An Artifact Signing account holds the identity validation and the"
  say "certificate profiles. Its name is globally unique, 3 to 24 letters and"
  say "digits, starting with a letter."
  note "Regions that support the service include eastus, westus2, westus3,"
  note "northeurope, westeurope, japaneast and koreacentral."
  ask AZURE_RESOURCE_GROUP "Resource group name [din-replicator-signing]:"
  AZURE_RESOURCE_GROUP="${AZURE_RESOURCE_GROUP:-din-replicator-signing}"
  ask AZURE_LOCATION "Region [westus2]:"
  AZURE_LOCATION="${AZURE_LOCATION:-westus2}"
  ask AZURE_ARTIFACT_SIGNING_ACCOUNT "Signing account name:"
  if [[ ! "$AZURE_ARTIFACT_SIGNING_ACCOUNT" =~ ^[A-Za-z][A-Za-z0-9]{2,23}$ ]]; then
    warn "that name does not fit Azure's rules for a signing account"
    exit 1
  fi

  if az "$AZ_SIGNING" show -g "$AZURE_RESOURCE_GROUP" \
      -n "$AZURE_ARTIFACT_SIGNING_ACCOUNT" >/dev/null 2>&1; then
    printf '  %s✓ found%s an existing signing account, using it\n' "$GREEN" "$RESET"
  else
    say "Creating the resource group and the signing account."
    az group create --name "$AZURE_RESOURCE_GROUP" --location "$AZURE_LOCATION" \
      --only-show-errors >/dev/null || true
    if ! az "$AZ_SIGNING" create -g "$AZURE_RESOURCE_GROUP" \
        -n "$AZURE_ARTIFACT_SIGNING_ACCOUNT" -l "$AZURE_LOCATION" --sku Basic \
        --only-show-errors >/dev/null; then
      warn "Azure would not create the account. Create it in the portal under"
      warn "Artifact Signing Accounts, then run the wizard again."
      open_url "https://portal.azure.com/#browse/Microsoft.CodeSigning%2FcodeSigningAccounts"
      DO_AZURE=false
    fi
  fi

  if [[ "$DO_AZURE" == true ]]; then
    # accountUri is the regional service endpoint the signing tool needs, for
    # example https://wus2.codesigning.azure.net.
    AZURE_ARTIFACT_SIGNING_ENDPOINT=$(az "$AZ_SIGNING" show \
      -g "$AZURE_RESOURCE_GROUP" -n "$AZURE_ARTIFACT_SIGNING_ACCOUNT" \
      --query accountUri -o tsv 2>/dev/null || true)
    if [[ -z "$AZURE_ARTIFACT_SIGNING_ENDPOINT" ]]; then
      say "The account does not report its endpoint. Read it from the account's"
      say "Overview pane in the portal."
      ask AZURE_ARTIFACT_SIGNING_ENDPOINT "Paste the endpoint URL:"
    fi
    printf '  %s✓ endpoint%s %s\n' "$GREEN" "$RESET" "$AZURE_ARTIFACT_SIGNING_ENDPOINT"
  fi
  pause "Press Enter for the next stage"
fi

# ── Stage 9 ───────────────────────────────────────────────────────────────
stage "Azure: identity validation and the certificate profile"
AZURE_ARTIFACT_SIGNING_CERTIFICATE_PROFILE=""
if [[ "$DO_AZURE" != true ]]; then
  skipped_stage "no signing account to add a certificate profile to"
else
  say "Microsoft will not issue a signing certificate until it has checked who"
  say "you are. Identity validation runs only in the portal and takes 1 to 20"
  say "business days. Start it now even if the rest has to wait."
  printf '\n'
  step "Open your signing account, then Objects > Identity validations."
  step "Choose Organization or Individual, click New Identity, then Public,"
  step "  and fill in the form. Follow the emails Microsoft sends."
  step "When the status reads Completed, open the entry and copy the value"
  step "  labelled Identity validation Id."
  note "The New Identity button is greyed out unless you hold the Artifact"
  note "Signing Identity Verifier role on the account."
  open_url "https://portal.azure.com/#browse/Microsoft.CodeSigning%2FcodeSigningAccounts"
  printf '\n'
  if ! confirm "Has identity validation finished?"; then
    say "That is fine. Nothing else here can be done yet."
    warn "Run this wizard again once the status reads Completed. Until then no"
    warn "Azure secret is stored, so a release still builds and the Windows"
    warn "installer comes out unsigned."
    DO_AZURE=false
    pause "Press Enter for the next stage"
  else
    ask AZURE_IDENTITY_VALIDATION_ID "Paste the Identity validation Id:"
    ask AZURE_ARTIFACT_SIGNING_CERTIFICATE_PROFILE "Name for the certificate profile [din-replicator]:"
    AZURE_ARTIFACT_SIGNING_CERTIFICATE_PROFILE="${AZURE_ARTIFACT_SIGNING_CERTIFICATE_PROFILE:-din-replicator}"

    if az "$AZ_SIGNING" certificate-profile show -g "$AZURE_RESOURCE_GROUP" \
        --account "$AZURE_ARTIFACT_SIGNING_ACCOUNT" \
        -n "$AZURE_ARTIFACT_SIGNING_CERTIFICATE_PROFILE" >/dev/null 2>&1; then
      printf '  %s✓ found%s an existing certificate profile, using it\n' "$GREEN" "$RESET"
    elif az "$AZ_SIGNING" certificate-profile create -g "$AZURE_RESOURCE_GROUP" \
        --account "$AZURE_ARTIFACT_SIGNING_ACCOUNT" \
        -n "$AZURE_ARTIFACT_SIGNING_CERTIFICATE_PROFILE" \
        --profile-type PublicTrust \
        --identity-validation-id "$AZURE_IDENTITY_VALIDATION_ID" \
        --only-show-errors >/dev/null; then
      printf '  %s✓ created%s the certificate profile\n' "$GREEN" "$RESET"
    else
      warn "Azure would not create the profile. Create it in the portal under"
      warn "Objects > Certificate profiles, choosing Public Trust, then run the"
      warn "wizard again."
      DO_AZURE=false
    fi
    pause "Press Enter for the next stage"
  fi
fi

# ── Stage 10 ──────────────────────────────────────────────────────────────
stage "Azure: the app registration that signs"
AZURE_CLIENT_ID=""
AZURE_TENANT_ID=""
AZURE_CLIENT_SECRET=""
if [[ "$DO_AZURE" != true ]]; then
  skipped_stage "no certificate profile for an app registration to sign with"
else
  say "The build runner signs in to Azure as an app registration rather than"
  say "as you, so signing does not depend on your own Azure sign-in."
  ask AZURE_APP_NAME "Name for the app registration [din-replicator-signing]:"
  AZURE_APP_NAME="${AZURE_APP_NAME:-din-replicator-signing}"

  AZURE_CLIENT_ID=$(az ad app list --display-name "$AZURE_APP_NAME" \
    --query "[0].appId" -o tsv 2>/dev/null || true)
  if [[ -z "$AZURE_CLIENT_ID" ]]; then
    AZURE_CLIENT_ID=$(az ad app create --display-name "$AZURE_APP_NAME" \
      --query appId -o tsv --only-show-errors 2>/dev/null || true)
    printf '  %s✓ created%s the app registration\n' "$GREEN" "$RESET"
  else
    printf '  %s✓ found%s an existing app registration with that name\n' "$GREEN" "$RESET"
  fi
  if [[ -z "$AZURE_CLIENT_ID" ]]; then
    warn "could not create the app registration. Your Azure account may not be"
    warn "allowed to register applications in this directory."
    DO_AZURE=false
  fi

  if [[ "$DO_AZURE" == true ]]; then
    # A role can only be assigned to a service principal, which is the
    # directory's local record of the application.
    if ! az ad sp show --id "$AZURE_CLIENT_ID" >/dev/null 2>&1; then
      az ad sp create --id "$AZURE_CLIENT_ID" --only-show-errors >/dev/null 2>&1 || true
    fi

    AZURE_TENANT_ID=$(az account show --query tenantId -o tsv)

    say "Adding a client secret. Azure shows a secret once, and this one goes"
    say "straight to GitHub without passing through the screen."
    AZURE_CLIENT_SECRET=$(az ad app credential reset --id "$AZURE_CLIENT_ID" \
      --append --years 1 --query password -o tsv --only-show-errors 2>/dev/null || true)
    if [[ -z "$AZURE_CLIENT_SECRET" ]]; then
      warn "could not add a client secret through the CLI. Add one in the"
      warn "portal under App registrations > your app > Certificates & secrets"
      warn "> New client secret, and copy the Value column."
      ask_secret AZURE_CLIENT_SECRET "Paste the client secret value:"
    else
      printf '  %s✓ added%s a client secret that expires in one year\n' "$GREEN" "$RESET"
    fi
    if [[ -z "$AZURE_CLIENT_SECRET" ]]; then
      warn "no client secret, so the Azure secrets will not be stored"
      DO_AZURE=false
    else
      warn "That secret expires in a year. Put the date in your calendar,"
      warn "because release builds start failing on the day it lapses."
    fi
  fi
  pause "Press Enter for the next stage"
fi

# ── Stage 11 ──────────────────────────────────────────────────────────────
stage "Azure: let the app registration sign"
if [[ "$DO_AZURE" != true ]]; then
  skipped_stage "no app registration to grant the signing role to"
else
  say "The app registration can do nothing until it holds the signing role on"
  say "the signing account."
  account_id=$(az "$AZ_SIGNING" show -g "$AZURE_RESOURCE_GROUP" \
    -n "$AZURE_ARTIFACT_SIGNING_ACCOUNT" --query id -o tsv 2>/dev/null || true)
  principal_id=$(az ad sp show --id "$AZURE_CLIENT_ID" --query id -o tsv 2>/dev/null || true)

  assigned=false
  if [[ -n "$account_id" && -n "$principal_id" ]]; then
    # Microsoft renamed the service, and a directory may still carry the role
    # under either name, so try both.
    for role in "Artifact Signing Certificate Profile Signer" \
                "Trusted Signing Certificate Profile Signer"; do
      if az role assignment create --assignee-object-id "$principal_id" \
          --assignee-principal-type ServicePrincipal --role "$role" \
          --scope "$account_id" --only-show-errors >/dev/null 2>&1; then
        printf '  %s✓ granted%s the %s role\n' "$GREEN" "$RESET" "$role"
        assigned=true
        break
      fi
    done
  fi

  if [[ "$assigned" != true ]]; then
    warn "the role assignment did not go through, so do it in the portal:"
    step "Open your signing account, then Access Control (IAM)."
    step "Click Add, then Add role assignment."
    step "On the Role tab search for Signing and select the role named"
    step "  Artifact Signing Certificate Profile Signer."
    step "On the Members tab set Assign access to to User, group, or service"
    step "  principal, click Select members, and pick $AZURE_APP_NAME."
    step "Click Review + assign."
    open_url "https://portal.azure.com/#browse/Microsoft.CodeSigning%2FcodeSigningAccounts"
    pause "Press Enter once the role is assigned"
  else
    pause "Press Enter for the next stage"
  fi
fi

# ── Stage 12 ──────────────────────────────────────────────────────────────
stage "GitHub: store the secrets"
say "Each value now goes to $GH_REPO as a GitHub Actions secret. GitHub hides"
say "them from workflow logs and never shows them again, not even to you."
printf '\n'
if ! command -v gh >/dev/null 2>&1; then
  warn "the GitHub CLI is not installed. Install it with: brew install gh"
elif ! gh auth status >/dev/null 2>&1; then
  warn "the GitHub CLI is not signed in. Sign in with: gh auth login"
fi

if [[ "${APPLE_SECRETS_STORED:-false}" == true ]]; then
  say "The six macOS secrets were stored at the end of the Apple stages."
elif [[ "$DO_APPLE" != true ]]; then
  SKIPPED+=("the six macOS secrets, so macOS builds stay unsigned")
fi

# The release workflow signs on Windows only when all six Azure secrets are
# set, so a half-finished Azure setup stores none of them.
if [[ "$DO_AZURE" == true ]]; then
  set_secret AZURE_TENANT_ID "$AZURE_TENANT_ID"
  set_secret AZURE_CLIENT_ID "$AZURE_CLIENT_ID"
  set_secret AZURE_CLIENT_SECRET "$AZURE_CLIENT_SECRET"
  set_secret AZURE_ARTIFACT_SIGNING_ENDPOINT "$AZURE_ARTIFACT_SIGNING_ENDPOINT"
  set_secret AZURE_ARTIFACT_SIGNING_ACCOUNT "$AZURE_ARTIFACT_SIGNING_ACCOUNT"
  set_secret AZURE_ARTIFACT_SIGNING_CERTIFICATE_PROFILE "$AZURE_ARTIFACT_SIGNING_CERTIFICATE_PROFILE"
else
  SKIPPED+=("the six Windows secrets, so Windows builds stay unsigned")
fi

printf '\n'
say "What GitHub holds for $GH_REPO now, names and dates only:"
printf '\n'
gh secret list 2>/dev/null || warn "could not list the secrets"
printf '\n'
pause "Press Enter for the summary"

finish

note "Next: cut a release with 'bun run release <version>', push the branch"
note "and then the tag, and watch the release workflow. docs/releasing.md has"
note "the commands that check a signed DMG and a signed installer."
printf '\n'
